/**
 * Application tables — everything that isn't Better Auth's own.
 *
 * Kept separate from auth-schema.ts because that file is REGENERATED by
 * `bun run auth:schema` and anything added there is lost. src/schema.ts
 * re-exports both; drizzle.config.ts and db.ts point at that union.
 *
 * Money is stored in micro-dollars (1e-6 USD) as bigints. Token prices are
 * fractions of a cent, and float drift in a billing ledger is unforgivable.
 */
import { relations } from "drizzle-orm";
import {
  bigint,
  bigserial,
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema.js";

/**
 * A key a robot uses to reach our inference proxy. Minted in the web app,
 * pasted into the runtime's config — this is the seam that lets the agent
 * keep running ON the robot while the model call is metered by US.
 *
 * Only the SHA-256 hash is stored. The raw key is shown once, at creation,
 * and is unrecoverable after: high-entropy random, so a fast hash is correct
 * here — bcrypt would tax every inference call for no added resistance.
 */
export const robotKey = pgTable(
  "robot_key",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Owner-supplied label: "Thor rig", "sim", "bench arm". */
    name: text("name").notNull(),
    /** Leading chars, safe to display so a key is identifiable in a list. */
    prefix: text("prefix").notNull(),
    hash: text("hash").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    lastUsedAt: timestamp("last_used_at"),
    /** Set instead of deleting, so past usage rows keep a valid parent. */
    revokedAt: timestamp("revoked_at"),
  },
  (t) => [
    uniqueIndex("robot_key_hash_idx").on(t.hash),
    index("robot_key_user_idx").on(t.userId),
  ],
);

/** Credits added to an account: signup allowance, top-up, manual grant. */
export const creditGrant = pgTable(
  "credit_grant",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    amountMicros: bigint("amount_micros", { mode: "number" }).notNull(),
    reason: text("reason").notNull(),
    /** When the owner was TOLD about this grant. Null is "not yet": the
     *  welcome credit is announced once, in a dialog, and "once" has to mean
     *  once per account and not once per browser — so it is a fact about the
     *  grant, kept here, and not a flag in localStorage. */
    seenAt: timestamp("seen_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("credit_grant_user_idx").on(t.userId)],
);

/**
 * One row per proxied model call. Balance is grants minus usage — a ledger,
 * never a mutated running total, so the number can always be re-derived and
 * every charge is traceable to the request that caused it.
 */
export const usage = pgTable(
  "usage",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    keyId: text("key_id").references(() => robotKey.id, { onDelete: "set null" }),
    model: text("model").notNull(),
    inputTokens: integer("input_tokens").notNull(),
    outputTokens: integer("output_tokens").notNull(),
    costMicros: bigint("cost_micros", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("usage_user_idx").on(t.userId)],
);

/**
 * A skill the agent authored on a robot, synced up for the registry.
 *
 * The robot runs from its own copy on disk; this row is the one that
 * outlives that disk. A browser whose IndexedDB was cleared, a new laptop,
 * a robot re-imaged — all of them read their skills back from here at boot,
 * so a taught skill is never lost with the machine it was taught on. Sync
 * failing must still never break a teach.
 *
 * Keyed per BODY (audit: platform is part of the key): a skill is written
 * for the arm it was taught on, and "wave" on the OpenArm is a different
 * program from "wave" on the RoArm. One user, one platform, one name.
 */
export const skill = pgTable(
  "skill",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description").notNull(),
    code: text("code").notNull(),
    platform: text("platform").notNull(),
    /** This exact code ran to completion at least once — the store's `.ran`
     *  mark, carried with the copy so a restored skill is listed the way it
     *  was listed where it was taught, not as a fresh unproven draft. */
    proven: boolean("proven").notNull().default(false),
    /** Listed on the public skill registry (botcortex.dev/skills). Set by
     *  the owner, only ever on a proven skill: the registry is the record
     *  of what has actually run, per arm, not a drafts folder. */
    published: boolean("published").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("skill_user_platform_name_idx").on(t.userId, t.platform, t.name)],
);

/**
 * A robot paired to an account.
 *
 * A row is born UNPAIRED during the device flow: the runtime describes itself
 * (name, platform, arms) against its secret device_code, so the approval screen
 * can say "Approve thor-rig (OpenArm v1)" instead of "approve unknown device".
 * That naming is the entire security value of the confirmation step, which is
 * why describe is authenticated by the unguessable device_code and not the
 * short user_code a shoulder-surfer could read.
 *
 * On registration the row gains its owner and key, and `userCode` is cleared.
 * The unique index only bites once `userId` is set — Postgres treats NULLs as
 * distinct — so half-finished pairings never collide with each other.
 */
export const robot = pgTable(
  "robot",
  {
    id: text("id").primaryKey(),
    /** Null until the pairing is approved and the robot registers. */
    userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
    /** Set during pairing so the approval page can find this row; cleared after. */
    userCode: text("user_code"),
    /**
     * SHA-256 of the device code, written at describe time and used by the
     * robot to claim this row after approval. We keep our own copy because
     * Better Auth DELETES the device code the moment it is redeemed (correct
     * single-use behaviour) — so by registration time there is nothing left
     * to join against. Hashed, not raw: it is a claim credential.
     */
    deviceCodeHash: text("device_code_hash"),
    name: text("name").notNull(),
    platform: text("platform").notNull(),
    arms: integer("arms").notNull().default(2),
    /** Last known LAN address for the web app's WebSocket, e.g. 192.168.1.42:9090. */
    address: text("address"),
    keyId: text("key_id").references(() => robotKey.id, { onDelete: "set null" }),
    lastSeenAt: timestamp("last_seen_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("robot_user_name_idx").on(t.userId, t.name),
    index("robot_user_code_idx").on(t.userCode),
  ],
);

export const robotRelations = relations(robot, ({ one }) => ({
  user: one(user, { fields: [robot.userId], references: [user.id] }),
  key: one(robotKey, { fields: [robot.keyId], references: [robotKey.id] }),
}));

/**
 * One thread of conversation with a robot.
 *
 * Threads exist so "New task" can start a fresh one instead of DELETING the
 * previous — which is what it did when the transcript was a single rolling
 * list, and which lost history a click at a time.
 *
 * The title is derived from the first thing the owner typed rather than asked
 * for, and set on that first message so an empty thread never renders as a
 * blank row.
 */
export const conversation = pgTable(
  "conversation",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title"),
    /** The body the task was taught on (a platform name such as roarm_m2).
     *  A task is a conversation with ONE robot: the sidebar lists the tasks
     *  of the robot that is connected, not everything the owner ever said
     *  to any robot. Null for tasks from before this was recorded. */
    platform: text("platform"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    /** Bumped on every message, so the sidebar sorts by recent activity. */
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("conversation_user_idx").on(t.userId, t.updatedAt),
    index("conversation_user_platform_idx").on(t.userId, t.platform),
  ],
);

export const conversationRelations = relations(conversation, ({ one, many }) => ({
  user: one(user, { fields: [conversation.userId], references: [user.id] }),
  messages: many(message),
}));

/**
 * The owner's conversation with their robot.
 *
 * Written by the WEB APP, not the runtime: the app sees both sides (what was
 * typed and what came back over the socket), where the runtime only knows its
 * own half. The cost is that a reply arriving after the tab closes is lost —
 * acceptable, since the SKILL it produced is already saved on the robot and in
 * the registry. The transcript is a record, not the artifact.
 *
 * `id` is generated client-side so persisting is idempotent: replaying a POST
 * conflicts on the primary key instead of duplicating the message.
 */
export const message = pgTable(
  "message",
  {
    id: text("id").primaryKey(),
    conversationId: text("conversation_id")
      .notNull()
      .references(() => conversation.id, { onDelete: "cascade" }),
    /**
     * Insertion order, and the ONLY thing the transcript is sorted by.
     *
     * created_at is not enough: a teach emits several lines in the same
     * millisecond, they tie, and `ORDER BY created_at LIMIT n` then returns
     * them in whatever order the planner feels like — which surfaced as a
     * test that passed alone and failed in a full run.
     */
    seq: bigserial("seq", { mode: "number" }).notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Which robot this was said to, when one was attached. */
    robotName: text("robot_name"),
    /** "you" | "robot" — mirrors the app's ChatMessage. */
    author: text("author").notNull(),
    /**
     * "text" | "tool". A tool row is one reach into the runtime — reading
     * joints, writing a skill, running it — kept so reopening a task shows
     * HOW a skill was authored, not just that it was.
     *
     * A column on `message` rather than a table of its own: traces then
     * inherit `seq`, so the transcript is one ordered query instead of two
     * lists merged on a timestamp.
     */
    kind: text("kind").notNull().default("text"),
    /** Human label for a tool row; the message itself for a text row. */
    text: text("text").notNull(),
    /** Tool detail: {name, input, result, ok}. Null for ordinary messages. */
    payload: jsonb("payload"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("message_convo_idx").on(t.conversationId, t.seq)],
);

export const messageRelations = relations(message, ({ one }) => ({
  user: one(user, { fields: [message.userId], references: [user.id] }),
  conversation: one(conversation, {
    fields: [message.conversationId],
    references: [conversation.id],
  }),
}));

export const robotKeyRelations = relations(robotKey, ({ one }) => ({
  user: one(user, { fields: [robotKey.userId], references: [user.id] }),
}));

export const usageRelations = relations(usage, ({ one }) => ({
  user: one(user, { fields: [usage.userId], references: [user.id] }),
  key: one(robotKey, { fields: [usage.keyId], references: [robotKey.id] }),
}));

export const skillRelations = relations(skill, ({ one }) => ({
  user: one(user, { fields: [skill.userId], references: [user.id] }),
}));

/**
 * The public face of an account: a handle, unique, that a skill page and an
 * author page can address (Sai, Sep 17). Its own table rather than a column on
 * `user`, because auth-schema.ts is regenerated and anything added there is
 * lost. A row appears the first time one is needed — most accounts never
 * publish anything and never get one.
 */
export const profile = pgTable("profile", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  handle: text("handle").notNull().unique(),
  /** What the person wants to be called in public. Null until they say; the
   *  sign-up name stands in until then. */
  firstName: text("first_name"),
  lastName: text("last_name"),
  bio: text("bio"),
  /** Seeds the generated avatar. Random, never derived from anything about
   *  the person: it is sent to a third-party image service in a URL. */
  avatarSeed: text("avatar_seed"),
  /** When they filled in (or skipped) the profile step. Null = ask once. */
  onboardedAt: timestamp("onboarded_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/**
 * Someone other than the author ran a published skill in their browser.
 *
 * What the registry is ranked by: a skill strangers keep running is a better
 * skill than a newer one nobody has. One row per skill, visitor and day, so
 * reloading a page is not a vote. `visitor` is a salted hash that changes
 * daily — never an address, and not linkable from one day to the next.
 */
export const skillRun = pgTable(
  "skill_run",
  {
    skillId: text("skill_id")
      .notNull()
      .references(() => skill.id, { onDelete: "cascade" }),
    visitor: text("visitor").notNull(),
    day: text("day").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.skillId, t.visitor, t.day] })],
);

/**
 * An owner's own model key (OpenAI or Anthropic), so teaching is paid for on
 * their account with the provider and not from BotCortex credit.
 *
 * Encrypted at rest (AES-256-GCM, see src/byok.ts) and used only inside the
 * inference proxy. Nothing ever sends it back: the app is shown which provider
 * it is for and its last four characters. One per account — a key is a way to
 * pay, and there is one way to pay at a time.
 */
export const modelKey = pgTable("model_key", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  provider: text("provider").notNull(),
  ciphertext: text("ciphertext").notNull(),
  last4: text("last4").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/**
 * One run of a skill, kept tick by tick as training data (the runtime's
 * botcortex/episodes.py). From a paired robot whose owner chose to share runs,
 * or from a signed-in browser tab.
 *
 * What is asked of this table is analysis across every robot and every body:
 * which skills fail, how, on what, and what repaired them. So everything worth
 * filtering on is a column. The trajectory itself (joint states, commanded
 * actions and object poses per control tick) is only ever read whole, so it is
 * stored as gzipped JSON, base64 in `ticks_gz`: about 12 KB an episode where
 * jsonb would be nearer 80. Images are never sent; in simulation they are a
 * function of the ticks and are rendered from them later.
 *
 * A failed episode and the run that repaired it name each other (`repairs`,
 * `repaired_by`), and both carry the skill's source as it stood: the pair is a
 * failure, the fix and the success on one task.
 *
 * The id is the runtime's, unique per account, not globally: two robots may
 * mint the same millisecond.
 */
export const episode = pgTable(
  "episode",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    id: text("id").notNull(),
    source: text("source").notNull(), // "robot" | "browser"
    platform: text("platform").notNull(),
    backend: text("backend").notNull(),
    skill: text("skill"),
    instruction: text("instruction"),
    phase: text("phase"),
    executed: boolean("executed").notNull().default(false),
    ok: boolean("ok").notNull(),
    kind: text("kind"),
    primitive: text("primitive"),
    note: text("note"),
    codeSha: text("code_sha"),
    code: text("code"),
    failureId: text("failure_id"),
    repairs: jsonb("repairs").$type<string[]>().notNull().default([]),
    repairedBy: text("repaired_by"),
    replays: text("replays"),
    length: integer("length").notNull(),
    fps: integer("fps").notNull(),
    /** Everything about the run that is not worth a column: params, the
     *  variation tried, joint and object names, the scene before and after. */
    detail: jsonb("detail").$type<Record<string, unknown>>().notNull().default({}),
    ticksGz: text("ticks_gz").notNull(),
    recordedAt: timestamp("recorded_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.id] }),
    index("episode_platform_skill_idx").on(t.platform, t.skill),
    index("episode_outcome_idx").on(t.ok, t.kind),
    index("episode_created_idx").on(t.createdAt),
  ],
);

const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType: () => "bytea",
  toDriver: (value) => value,
  fromDriver: (value) => value,
});

/**
 * What an episode carries that is not numbers: camera footage from a real arm,
 * which cannot be re-rendered the way a simulator's can.
 *
 * A file arrives in parts, because the API runs behind a 4.5 MB request limit
 * and a minute of video is more than that. Each part is a row until the last
 * one lands; where the bytes finally live is `storage`:
 *
 *   "supabase"  an object in the episodes bucket (SUPABASE_URL +
 *               SUPABASE_SERVICE_ROLE_KEY set) — `bytes` stays null
 *   "database"  right here. Correct, and not where footage belongs at scale:
 *               Postgres on the free tier is 500 MB and a filmed episode is
 *               about one. It is the fallback that keeps nothing from being
 *               lost before a bucket exists.
 */
export const episodeBlob = pgTable(
  "episode_blob",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    episodeId: text("episode_id").notNull(),
    name: text("name").notNull(),
    part: integer("part").notNull(),
    parts: integer("parts").notNull(),
    size: integer("size").notNull(),
    storage: text("storage").notNull(),
    bytes: bytea("bytes"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.episodeId, t.name, t.part] })],
);
