/**
 * Application tables — everything that isn't Better Auth's own.
 *
 * Kept separate from auth-schema.ts because that file is REGENERATED by
 * `bun run auth:schema` and anything added there is lost. src/schema.ts
 * re-exports both; drizzle.config.ts and db.ts point at that union.
 *
 * Money is stored in micro-dollars (1e-6 USD) as bigints. Token prices are
 * fractions of a cent, and float drift in a billing ledger is unforgivable.
 */
import { relations } from "drizzle-orm";
import {
  bigint,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema.js";

/**
 * A key a robot uses to reach our inference proxy. Minted in the web app,
 * pasted into the runtime's config — this is the seam that lets the agent
 * keep running ON the robot while the model call is metered by US.
 *
 * Only the SHA-256 hash is stored. The raw key is shown once, at creation,
 * and is unrecoverable after: high-entropy random, so a fast hash is correct
 * here — bcrypt would tax every inference call for no added resistance.
 */
export const robotKey = pgTable(
  "robot_key",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Owner-supplied label: "Thor rig", "sim", "bench arm". */
    name: text("name").notNull(),
    /** Leading chars, safe to display so a key is identifiable in a list. */
    prefix: text("prefix").notNull(),
    hash: text("hash").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    lastUsedAt: timestamp("last_used_at"),
    /** Set instead of deleting, so past usage rows keep a valid parent. */
    revokedAt: timestamp("revoked_at"),
  },
  (t) => [
    uniqueIndex("robot_key_hash_idx").on(t.hash),
    index("robot_key_user_idx").on(t.userId),
  ],
);

/** Credits added to an account: signup allowance, top-up, manual grant. */
export const creditGrant = pgTable(
  "credit_grant",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    amountMicros: bigint("amount_micros", { mode: "number" }).notNull(),
    reason: text("reason").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("credit_grant_user_idx").on(t.userId)],
);

/**
 * One row per proxied model call. Balance is grants minus usage — a ledger,
 * never a mutated running total, so the number can always be re-derived and
 * every charge is traceable to the request that caused it.
 */
export const usage = pgTable(
  "usage",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    keyId: text("key_id").references(() => robotKey.id, { onDelete: "set null" }),
    model: text("model").notNull(),
    inputTokens: integer("input_tokens").notNull(),
    outputTokens: integer("output_tokens").notNull(),
    costMicros: bigint("cost_micros", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("usage_user_idx").on(t.userId)],
);

/**
 * A skill the agent authored on a robot, synced up for the registry.
 *
 * The robot keeps the original on disk and runs from there — this is a copy,
 * not the source of truth. Sync failing must never break a teach.
 */
export const skill = pgTable(
  "skill",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description").notNull(),
    code: text("code").notNull(),
    platform: text("platform").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("skill_user_name_idx").on(t.userId, t.name)],
);

export const robotKeyRelations = relations(robotKey, ({ one }) => ({
  user: one(user, { fields: [robotKey.userId], references: [user.id] }),
}));

export const usageRelations = relations(usage, ({ one }) => ({
  user: one(user, { fields: [usage.userId], references: [user.id] }),
  key: one(robotKey, { fields: [usage.keyId], references: [robotKey.id] }),
}));

export const skillRelations = relations(skill, ({ one }) => ({
  user: one(user, { fields: [skill.userId], references: [user.id] }),
}));
