/**
 * Application tables — everything that isn't Better Auth's own.
 *
 * Kept separate from auth-schema.ts because that file is REGENERATED by
 * `bun run auth:schema` and anything added there is lost. src/schema.ts
 * re-exports both; drizzle.config.ts and db.ts point at that union.
 *
 * Money is stored in micro-dollars (1e-6 USD) as bigints. Token prices are
 * fractions of a cent, and float drift in a billing ledger is unforgivable.
 */
import { relations } from "drizzle-orm";
import {
  bigint,
  bigserial,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema.js";

/**
 * A key a robot uses to reach our inference proxy. Minted in the web app,
 * pasted into the runtime's config — this is the seam that lets the agent
 * keep running ON the robot while the model call is metered by US.
 *
 * Only the SHA-256 hash is stored. The raw key is shown once, at creation,
 * and is unrecoverable after: high-entropy random, so a fast hash is correct
 * here — bcrypt would tax every inference call for no added resistance.
 */
export const robotKey = pgTable(
  "robot_key",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Owner-supplied label: "Thor rig", "sim", "bench arm". */
    name: text("name").notNull(),
    /** Leading chars, safe to display so a key is identifiable in a list. */
    prefix: text("prefix").notNull(),
    hash: text("hash").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    lastUsedAt: timestamp("last_used_at"),
    /** Set instead of deleting, so past usage rows keep a valid parent. */
    revokedAt: timestamp("revoked_at"),
  },
  (t) => [
    uniqueIndex("robot_key_hash_idx").on(t.hash),
    index("robot_key_user_idx").on(t.userId),
  ],
);

/** Credits added to an account: signup allowance, top-up, manual grant. */
export const creditGrant = pgTable(
  "credit_grant",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    amountMicros: bigint("amount_micros", { mode: "number" }).notNull(),
    reason: text("reason").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("credit_grant_user_idx").on(t.userId)],
);

/**
 * One row per proxied model call. Balance is grants minus usage — a ledger,
 * never a mutated running total, so the number can always be re-derived and
 * every charge is traceable to the request that caused it.
 */
export const usage = pgTable(
  "usage",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    keyId: text("key_id").references(() => robotKey.id, { onDelete: "set null" }),
    model: text("model").notNull(),
    inputTokens: integer("input_tokens").notNull(),
    outputTokens: integer("output_tokens").notNull(),
    costMicros: bigint("cost_micros", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("usage_user_idx").on(t.userId)],
);

/**
 * A skill the agent authored on a robot, synced up for the registry.
 *
 * The robot keeps the original on disk and runs from there — this is a copy,
 * not the source of truth. Sync failing must never break a teach.
 */
export const skill = pgTable(
  "skill",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description").notNull(),
    code: text("code").notNull(),
    platform: text("platform").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("skill_user_name_idx").on(t.userId, t.name)],
);

/**
 * A robot paired to an account.
 *
 * A row is born UNPAIRED during the device flow: the runtime describes itself
 * (name, platform, arms) against its secret device_code, so the approval screen
 * can say "Approve thor-rig (OpenArm v1)" instead of "approve unknown device".
 * That naming is the entire security value of the confirmation step, which is
 * why describe is authenticated by the unguessable device_code and not the
 * short user_code a shoulder-surfer could read.
 *
 * On registration the row gains its owner and key, and `userCode` is cleared.
 * The unique index only bites once `userId` is set — Postgres treats NULLs as
 * distinct — so half-finished pairings never collide with each other.
 */
export const robot = pgTable(
  "robot",
  {
    id: text("id").primaryKey(),
    /** Null until the pairing is approved and the robot registers. */
    userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
    /** Set during pairing so the approval page can find this row; cleared after. */
    userCode: text("user_code"),
    /**
     * SHA-256 of the device code, written at describe time and used by the
     * robot to claim this row after approval. We keep our own copy because
     * Better Auth DELETES the device code the moment it is redeemed (correct
     * single-use behaviour) — so by registration time there is nothing left
     * to join against. Hashed, not raw: it is a claim credential.
     */
    deviceCodeHash: text("device_code_hash"),
    name: text("name").notNull(),
    platform: text("platform").notNull(),
    arms: integer("arms").notNull().default(2),
    /** Last known LAN address for the web app's WebSocket, e.g. 192.168.1.42:9090. */
    address: text("address"),
    keyId: text("key_id").references(() => robotKey.id, { onDelete: "set null" }),
    lastSeenAt: timestamp("last_seen_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("robot_user_name_idx").on(t.userId, t.name),
    index("robot_user_code_idx").on(t.userCode),
  ],
);

export const robotRelations = relations(robot, ({ one }) => ({
  user: one(user, { fields: [robot.userId], references: [user.id] }),
  key: one(robotKey, { fields: [robot.keyId], references: [robotKey.id] }),
}));

/**
 * One thread of conversation with a robot.
 *
 * Threads exist so "New task" can start a fresh one instead of DELETING the
 * previous — which is what it did when the transcript was a single rolling
 * list, and which lost history a click at a time.
 *
 * The title is derived from the first thing the owner typed rather than asked
 * for, and set on that first message so an empty thread never renders as a
 * blank row.
 */
export const conversation = pgTable(
  "conversation",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    /** Bumped on every message, so the sidebar sorts by recent activity. */
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [index("conversation_user_idx").on(t.userId, t.updatedAt)],
);

export const conversationRelations = relations(conversation, ({ one, many }) => ({
  user: one(user, { fields: [conversation.userId], references: [user.id] }),
  messages: many(message),
}));

/**
 * The owner's conversation with their robot.
 *
 * Written by the WEB APP, not the runtime: the app sees both sides (what was
 * typed and what came back over the socket), where the runtime only knows its
 * own half. The cost is that a reply arriving after the tab closes is lost —
 * acceptable, since the SKILL it produced is already saved on the robot and in
 * the registry. The transcript is a record, not the artifact.
 *
 * `id` is generated client-side so persisting is idempotent: replaying a POST
 * conflicts on the primary key instead of duplicating the message.
 */
export const message = pgTable(
  "message",
  {
    id: text("id").primaryKey(),
    conversationId: text("conversation_id")
      .notNull()
      .references(() => conversation.id, { onDelete: "cascade" }),
    /**
     * Insertion order, and the ONLY thing the transcript is sorted by.
     *
     * created_at is not enough: a teach emits several lines in the same
     * millisecond, they tie, and `ORDER BY created_at LIMIT n` then returns
     * them in whatever order the planner feels like — which surfaced as a
     * test that passed alone and failed in a full run.
     */
    seq: bigserial("seq", { mode: "number" }).notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Which robot this was said to, when one was attached. */
    robotName: text("robot_name"),
    /** "you" | "robot" — mirrors the app's ChatMessage. */
    author: text("author").notNull(),
    text: text("text").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [index("message_convo_idx").on(t.conversationId, t.seq)],
);

export const messageRelations = relations(message, ({ one }) => ({
  user: one(user, { fields: [message.userId], references: [user.id] }),
  conversation: one(conversation, {
    fields: [message.conversationId],
    references: [conversation.id],
  }),
}));

export const robotKeyRelations = relations(robotKey, ({ one }) => ({
  user: one(user, { fields: [robotKey.userId], references: [user.id] }),
}));

export const usageRelations = relations(usage, ({ one }) => ({
  user: one(user, { fields: [usage.userId], references: [user.id] }),
  key: one(robotKey, { fields: [usage.keyId], references: [robotKey.id] }),
}));

export const skillRelations = relations(skill, ({ one }) => ({
  user: one(user, { fields: [skill.userId], references: [user.id] }),
}));
