/**
 * The full schema — the union drizzle-kit generates from and db.ts queries
 * through. auth-schema.ts is generated by `bun run auth:schema` and must not
 * be hand-edited; app-schema.ts holds everything else.
 */
export * from "./auth-schema.js";
export * from "./app-schema.js";
